config/routes.rb
Rails.application.routes.draw do
  
  
  get '/admin/login', to: 'sessions#new_admin'
  post '/admin/login', to: 'sessions#create_new_admin'

  get 'admin/addcustomer', to: 'admin#new_user_form'
  post 'admin/create_customer', to: 'admin#create_new_user'
  get  'admin/show_customer',   to: 'admin#show_customer'

  get 'admin/create'

  get 'admin/update'

  get 'admin/edit'

  get 'admin/destroy'

  get 'orders/new'

  get 'orders/show'
  

  root 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/bagged',  to: 'static_pages#bagged'
  get '/contact', to: 'static_pages#contact'
  get '/menus',   to: 'static_pages#menus'
  get '/offers',  to: 'static_pages#offers'

  resources :users do
    resources :addresses
  end

  get  '/signup',   to: 'users#new'
  post '/signup',   to: 'users#create'

  get     '/user/login',  to: 'sessions#new_user'
  post    '/user/login',  to: 'sessions#create_new_user'
  delete  '/logout', to: 'sessions#destroy'

  get '/newreservation', to: 'reservations#new'

  resources :items
  get  '/additem',       to: 'items#new'
  post '/additem',       to: 'items#create'
  get 'admin/dashboard', to: 'admin#dashboard'
  
   
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def bagged
  end

  def contact
  end

  def home
  end

  def menus
  end

  def offers
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>Why is everyone talking about a comeback?</h1>

app/views/static_pages/bagged.html.erb
<% provide(:title, "Bagged") %>

<h1>Get your togo or delivery here.</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact us for the good or the bad.</h1>

app/views/static_pages/home.html.erb
<div class="center jumbotron" style="background-image: url(<%= asset_path'bg_3.jpg' %>); background-size: 151%; height: 500px; background-repeat: no-repeat;">
  <h1>Welcome to Roy's Place</h1>
  <br>
  <% provide(:title, "Home") %>
  <% if !logged_in? %>
 <%= link_to "Register to Order Pickup or Delivery!", signup_path, class: "btn btn-lg btn-primary" %>
  <br>
  <br>
  <% end %>

  <%= link_to "Schedule your Booking", newreservation_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("roysplacelogo.png", alt: "Roy's Place logo"),
'http://roysplace.com/' %>

app/views/static_pages/menus.html.erb
<% provide(:title, "Menus") %>

<h1>StaticPages#menus</h1>
<p>Find me in app/views/static_pages/menus.html.erb</p>

app/views/static_pages/offers.html.erb
<% provide(:title, "Offers") %>

<h1>StaticPages#offers</h1>
<p>Find me in app/views/static_pages/offers.html.erb</p>