config/routes.rb
Rails.application.routes.draw do
  
  
  get '/admin/login', to: 'sessions#new_admin'
  post '/admin/login', to: 'sessions#create_new_admin'

  get 'admin/addcustomer', to: 'admin#new_user_form'
  post 'admin/create_customer', to: 'admin#create_new_user'
  get  'admin/show_customer',   to: 'admin#show_customer'

  get 'admin/create'

  get 'admin/update'

  get 'admin/edit'

  get 'admin/destroy'

  get 'orders/new'

  get 'orders/show'
  

  root 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/bagged',  to: 'static_pages#bagged'
  get '/contact', to: 'static_pages#contact'
  get '/menus',   to: 'static_pages#menus'
  get '/offers',  to: 'static_pages#offers'

  resources :users do
    resources :addresses
  end

  get  '/signup',   to: 'users#new'
  post '/signup',   to: 'users#create'

  get     '/user/login',  to: 'sessions#new_user'
  post    '/user/login',  to: 'sessions#create_new_user'
  delete  '/logout', to: 'sessions#destroy'

  get '/newreservation', to: 'reservations#new'

  resources :items
  get  '/additem',       to: 'items#new'
  post '/additem',       to: 'items#create'
  get 'admin/dashboard', to: 'admin#dashboard'
  
   
end

app/models/item.rb
class Item < ApplicationRecord
  before_save { self.item_name = item_name.capitalize }
  before_save { self.description = description.capitalize }
  before_save { self.modifiers = modifiers.capitalize }

      
  enum menu: [:Breakfast, :Lunch, :HappyHour, :Dinner, :LateNight, :Brunch, :Catering]
  enum section: [:Starters, :Classics, :Dishes, :A_La_Carte, :Confections]

  VALID_PRICE_REGEX = /^\d{1,4}(\.\d{0,2})?$/

  validates :item_name,    presence: true, length: { maximum: 50 }  
  validates :description,  presence: true, length: { maximum: 250 }
  validates :price,        presence: true, numericality: { greater_than: 0.0},
                           format: { with: VALID_PRICE_REGEX, multiline: true }
  validates :modifiers,    presence: true, length: { maximum: 75 }
  validates :menu,         presence: true, if: :type_of_menu?
  validates :section,      presence: true
  validates :availability, presence: true                   

  #returns true if menu includes one of the enum above
  def type_of_menu?
    menu.include?(menu)
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user 
  before_action :admin_user
  layout "admin"

  def new
    @item = Item.new
  end

  def show
  end 

  def create
    @item = Item.new(item_params)
      if @item.save
        flash[:success] = "The following item was successfully added to menu!"
        redirect_to @item
      else
        render 'new'
      end
  end

  def edit
  end

  def update
    if @item.update_attributes(item_params)
       flash[:success] = "#{@item.item_name} information was updated successfully!"
       redirect_to @item
      else
        render 'edit'
      end
    
  end

  private
  def item_params
    params.require(:item).permit(:id, :item_name, :description, :price, 
                                  :modifiers, :section, :menu, :availability)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to admin_login_url
      end
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<% provide(:title, "Edit Item") %>
<% provide(:button_text, "Save changes") %>
<% provide(:path, item_path) %>

<h1>Update your item here</h1>
<%= render 'items/partials/item_info_layout' %>

app/views/items/new.html.erb
<% provide(:title, 'Add Item') %>
<% provide(:button_text, 'Create Item') %>
<% provide(:path, additem_path) %> 
<%= render 'items/partials/item_info_form' %>

app/views/items/show.html.erb
<% provide(:title, 'Show Item') %>
<h1></h1>
<ul class="list-group">
  <li class="list-group-item active">Item's Name: <%= @item.item_name %> </li>
  <li class="list-group-item ">Item's Description: <%= @item.description %></li>
  <li class="list-group-item active">Item's Price: <%= @item.price %></li>
  <li class="list-group-item">Item's Modifiers: <%= @item.modifiers %></li>
  <li class="list-group-item active">Item's Menu: <%= @item.menu %></li>
  <li class="list-group-item">Item's Section: <%= @item.section %></li>
  <% if @item.availability %>
  <li class="list-group-item active">Item's Availability: Yes</li>
  <% else %>
  <li class="list-group-item active">Item's Availability: No</li>
  <% end %>
</ul>


<%= link_to "Edit", edit_item_path(@item), class: "btn btn-lg btn-primary" %>