config/routes.rb
Rails.application.routes.draw do
  
  
  get '/admin/login', to: 'sessions#new_admin'
  post '/admin/login', to: 'sessions#create_new_admin'

  get 'admin/addcustomer', to: 'admin#new_user_form'
  post 'admin/create_customer', to: 'admin#create_new_user'
  get  'admin/show_customer',   to: 'admin#show_customer'

  get 'admin/create'

  get 'admin/update'

  get 'admin/edit'

  get 'admin/destroy'

  get 'orders/new'

  get 'orders/show'
  

  root 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/bagged',  to: 'static_pages#bagged'
  get '/contact', to: 'static_pages#contact'
  get '/menus',   to: 'static_pages#menus'
  get '/offers',  to: 'static_pages#offers'

  resources :users do
    resources :addresses
  end

  get  '/signup',   to: 'users#new'
  post '/signup',   to: 'users#create'

  get     '/user/login',  to: 'sessions#new_user'
  post    '/user/login',  to: 'sessions#create_new_user'
  delete  '/logout', to: 'sessions#destroy'

  get '/newreservation', to: 'reservations#new'

  resources :items
  get  '/additem',       to: 'items#new'
  post '/additem',       to: 'items#create'
  get 'admin/dashboard', to: 'admin#dashboard'
  
   
end

app/views/layouts/_admin_footer.html.erb
<footer class="navbaradmin navbaradmin-inverse navbar-fixed-bottom>
<div class="container">
      <div class="navbaradmin-header">
        <a class="navbaradmin-brand" href="#">Roy's Place</a>
      </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", admin_dashboard_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Customers <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Add Customer",  admin_addcustomer_path %></li>
              <li><%= link_to "Update Customer", "#" %></li>
              <li><a href="#">Delete Customer</a></li>
              <li><a href="#">Search Customer</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Items <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Add Item",  new_item_path %></li>
              <li><%= link_to "Update Item", "#" %></li>
              <li><a href="#">Delete Item</a></li>
              <li><a href="#">Search Item</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menus <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Breakfast</a></li>
              <li><a href="#">Lunch</a></li>
              <li><a href="#">Happy Hour</a></li>
              <li><a href="#">Dinner</a></li>
              <li><a href="#">Late Night</a></li>
              <li><a href="#">Brunch</a></li>
              <li><a href="#">Catering</a></li>
            </ul>
          </li>
        </ul>
        
      </div>
    </div>

</footer>

app/views/layouts/_admin_header.html.erb
<header class="navbaradmin navbaradmin-inverse navbar-fixed-bottom>
  <div class="container">
    <div class="navbaradmin-header">
      <a class="navbaradmin-brand" href="#">Roy's Place</a>
        <ul class="nav navbar-nav">
          <li><%= link_to "Home",  admin_dashboard_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Customers <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Add Customer",  admin_addcustomer_path %></li>
              <li><%= link_to "Update Customer", "#" %></li>
              <li><a href="#">Delete Customer</a></li>
              <li><a href="#">Search Customer</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Items <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Add Item",  new_item_path %></li>
              <li><%= link_to "Update Item", "#" %></li>
              <li><a href="#">Delete Item</a></li>
              <li><a href="#">Search Item</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menus <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Breakfast</a></li>
              <li><a href="#">Lunch</a></li>
              <li><a href="#">Happy Hour</a></li>
              <li><a href="#">Dinner</a></li>
              <li><a href="#">Late Night</a></li>
              <li><a href="#">Brunch</a></li>
              <li><a href="#">Catering</a></li>
            </ul>
          </li>
          <li>
          <% if logged_in? %>
            <%= render 'admin/partials/account' %>
          <% else %>
            <%= link_to "Login", admin_login_path %>
          <% end %>
          </li>
        </ul>
      </div>
  </div>
</header>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
      Roy's place, A sandwich heaven, yummie!    
    </small>
    <nav>
      <ul>
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Menus",   menus_path %></li>
        <li><%= link_to "Bagged",  bagged_path %></li>
        <li><%= link_to "Offers",  offers_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Sign Up",  signup_path %></li>
      </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-left navbar-inverse">
      <div class="container">
        <%= link_to "Roy's Place", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",    root_path %></li>
            <%= render 'layouts/drop_down/about' %>
            <%= render 'layouts/drop_down/menus' %>
            <%= render 'layouts/drop_down/bagged' %>
            <%= render 'layouts/drop_down/offers' %>
            <%= render 'layouts/drop_down/engageus' %> 
            <% if logged_in? %>
            <%= render 'layouts/drop_down/account' %>
            <% else %>
            <li><%= link_to "LogIn", user_login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roysplace</title>
    <title><%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/admin_header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
                <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>     
    <%= yield %>
    </div>
    <%= render 'layouts/admin_footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roysplace</title>
    <title><%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>     
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %> 
    <%= debug(params) if Rails.env.development? %>
  </body>

</html>